- name: Ensure the salt variable has a default value
  set_fact:
    salt: "{{ salt | default('mysalt') }}"

- name: Hash the password with a salt
  set_fact:
    hashed_password: "{{ plain_password | password_hash('sha512', salt) }}"

- name: Change user password
  user:
    name: "{{ username }}"
    password: "{{ hashed_password }}"
    update_password: always
    state: present
    shell: /bin/bash
  become: true # true to run as root
